### ISSUE TITLE
Missing Interface - STEAMUNIFIEDMESSAGES

### ISSUE THREAD

**Issue by ghost** [Detanup01/gbe_fork#123]
Hey,

I've been trying to get Star of Providence working without success. I created the steam_interfaces file with the provided tool, but the message doesn't go away.

![missing_interfaces](https://github.com/user-attachments/assets/42e22bda-2f77-488d-886b-09435d43c5b3)

I'm using the 2024-12-07 Experimental release.

**Comment by universal963** [comment]
Duplicate of #72. Remove line "SteamClient020" in `steam_interfaces.txt` and try again.

**Comment by ghost** [comment]
That worked, thank you!
