### ISSUE TITLE
A small question about the DLLs

### ISSUE THREAD

**Issue by egornovivan** [Detanup01/gbe_fork#126]
What are these dll files? Without them, some games do not work, and there is no information about these dlls

![изображение](https://github.com/user-attachments/assets/9ce7240e-db81-421e-b6a6-a6b0ede16dbd)

**Comment by DogancanYr** [comment]
They exist to bypass Steamstub drm.

**Comment by otavepto** [comment]
@egornovivan Always check the readme files bundled with each release: https://github.com/Detanup01/gbe_fork/blob/dev/post_build/README.experimental_steamclient.md#extra_dlls

**Comment by egornovivan** [comment]
Sorry, I didn't notice this in the readme
