### ISSUE TITLE
Emulation of online functions (lobby search) via spacewar (480)

### ISSUE THREAD

**Issue by kolan2222** [Detanup01/gbe_fork#127]
I have a question. Is it possible to realize emulation of online functions via spacewar (480)? Connection to the lobby, available when the game is running through Steam. But in this case, the game saves are in its original appid, but Steam would think that running spacewar. 
That would be a very nice addition to this emulator. Or explain how to do it if it is already implemented.

**Comment by Detanup01** [comment]
See #94

**Comment by kolan2222** [comment]
cream api seems to have been blocked because of the DMCA. And it only scans installed games. It doesn't seem to be able to add a side game.
Is it possible through the injection of .dll through the folder somehow to implement this function and try to trick Steam? Or not? I don't know anything about the API Steam.

**Comment by TheBotlyNoob** [comment]
The point of this project is to enable LAN-only play, such as in LAN parties or families playing together. Leave the online stuff to online-fix and the likes. Like @Detanup01 said previously, this is an open source project that you are free to fork and modify to your liking.

**Comment by kolan2222** [comment]
Okay. Thanks. I guess if I or someone comes up with a universal solution, we'll know for sure.
