### ISSUE TITLE
Error to build src VS2022 

### ISSUE THREAD

**Issue by Chichimokers** [Detanup01/gbe_fork#22]
well this is the log of build dependences 
![image](https://github.com/user-attachments/assets/1223ad6c-5368-4883-850b-edac87841658)
when i run build_win_premake.bat this happend Generating from .proto file!
Success!
Building configurations...
Running action 'vs2022'...
Generated build/project/vs2022/win/api_regular/api_regular.vcxproj...
Generated build/project/vs2022/win/api_experimental/api_experimental.vcxproj...
Generated build/project/vs2022/win/steamclient_experimental/steamclient_experimental.vcxproj...
Generated build/project/vs2022/win/tool_lobby_connect/tool_lobby_connect.vcxproj...
Generated build/project/vs2022/win/tool_generate_interfaces/tool_generate_interfaces.vcxproj...
Generated build/project/vs2022/win/lib_steamnetworkingsockets/lib_steamnetworkingsockets.vcxproj...
Generated build/project/vs2022/win/lib_game_overlay_renderer/lib_game_overlay_renderer.vcxproj...
Generated build/project/vs2022/win/steamclient_experimental_stub/steamclient_experimental_stub.vcxproj...
Generated build/project/vs2022/win/steamclient_experimental_extra/steamclient_experimental_extra.vcxproj...
Generated build/project/vs2022/win/steamclient_experimental_loader/steamclient_experimental_loader.vcxproj...
Generated build/project/vs2022/win/tool_file_dos_stub_changer/tool_file_dos_stub_changer.vcxproj...
Generated build/project/vs2022/win/test_crash_printer/test_crash_printer.vcxproj...
Done (3532ms).

 building api_regular release x64
Compilación iniciada a las 19/08/2024 11:17:52:AM.
     1>Proyecto "D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\project\vs2022\win\gbe.sln" en el nodo 1 (api_regul
       ar destinos).
     1>ValidateSolutionConfiguration:
         Compilando la configuración de soluciones "release|x64".
     1>El proyecto "D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\project\vs2022\win\gbe.sln" (1) está compilando
       "D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.vcxproj" (2) en e
       l nodo 1 (destinos predeterminados).
     2>InitializeBuildStatus:
         Aplicando tarea Touch a "obj\x64\release\api_regular.tlog\unsuccessfulbuild".
       ClCompile:
         C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.30.30705\bin\HostX86\x64\CL.exe /c
          /I..\..\..\..\..\dll /I..\..\..\..\..\proto_gen\win /I..\..\..\..\..\libs /I..\..\..\..\..\libs\utfcpp /I..\.
         .\..\..\..\helpers /I..\..\..\..\..\crash_printer /I..\..\..\..\..\sdk /I..\..\..\..\..\overlay_experimental /
         I..\..\..\..\deps\win\vs2022\libssq\include /I..\..\..\..\deps\win\vs2022\curl\install64\include /I..\..\..\..
         \deps\win\vs2022\protobuf\install64\include /I..\..\..\..\deps\win\vs2022\zlib\install64\include /I..\..\..\..
         \deps\win\vs2022\mbedtls\install64\include /nologo /W3 /WX- /diagnostics:column /MP4 /Ox /Oi /D UTF_CPP_CPLUSP
         LUS=201703L /D CURL_STATICLIB /D CONTROLLER_SUPPORT /D "EMU_BUILD_STRING=2024_08_19-11_17_48" /D NDEBUG /D EMU
         _RELEASE_BUILD /D _CRT_SECURE_NO_WARNINGS /D _WINDLL /D _UNICODE /D UNICODE /GF /Gm- /EHsc /MT /GS /Gy /fp:pre
         cise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Fo"obj\x64\release\\" /Fd"obj\x64\release\vc143.pdb" /ext
         ernal:W3 /Gd /TP /FC /errorReport:queue /permissive- /DYNAMICBASE /bigobj /utf-8 /Zc:char8_t- /EHsc /GL- ..\..
         \..\..\..\crash_printer\win.cpp ..\..\..\..\..\dll\appticket.cpp ..\..\..\..\..\dll\auth.cpp ..\..\..\..\..\dl
         l\base.cpp ..\..\..\..\..\dll\callsystem.cpp ..\..\..\..\..\dll\dll.cpp ..\..\..\..\..\dll\flat.cpp ..\..\..\.
         .\..\dll\local_storage.cpp ..\..\..\..\..\dll\network.cpp ..\..\..\..\..\dll\settings.cpp ..\..\..\..\..\dll\s
         ettings_parser.cpp ..\..\..\..\..\dll\source_query.cpp ..\..\..\..\..\dll\steam_HTMLsurface.cpp ..\..\..\..\..
         \dll\steam_app_ids.cpp ..\..\..\..\..\dll\steam_applist.cpp ..\..\..\..\..\dll\steam_apps.cpp ..\..\..\..\..\d
         ll\steam_client.cpp ..\..\..\..\..\dll\steam_client_interface_getter.cpp ..\..\..\..\..\dll\steam_controller.c
         pp ..\..\..\..\..\dll\steam_friends.cpp ..\..\..\..\..\dll\steam_game_coordinator.cpp ..\..\..\..\..\dll\steam
         _gamesearch.cpp ..\..\..\..\..\dll\steam_gameserver.cpp ..\..\..\..\..\dll\steam_gameserverstats.cpp ..\..\..\
         ..\..\dll\steam_gamestats.cpp ..\..\..\..\..\dll\steam_http.cpp ..\..\..\..\..\dll\steam_inventory.cpp ..\..\.
         .\..\..\dll\steam_masterserver_updater.cpp ..\..\..\..\..\dll\steam_matchmaking.cpp ..\..\..\..\..\dll\steam_m
         atchmaking_servers.cpp ..\..\..\..\..\dll\steam_music.cpp ..\..\..\..\..\dll\steam_musicremote.cpp ..\..\..\..
         \..\dll\steam_networking.cpp ..\..\..\..\..\dll\steam_networking_messages.cpp ..\..\..\..\..\dll\steam_network
         ing_sockets.cpp ..\..\..\..\..\dll\steam_networking_socketsserialized.cpp ..\..\..\..\..\dll\steam_networking_
         utils.cpp ..\..\..\..\..\dll\steam_parental.cpp ..\..\..\..\..\dll\steam_parties.cpp ..\..\..\..\..\dll\steam_
         remote_storage.cpp ..\..\..\..\..\dll\steam_remoteplay.cpp ..\..\..\..\..\dll\steam_screenshots.cpp ..\..\..\.
         .\..\dll\steam_timeline.cpp ..\..\..\..\..\dll\steam_tv.cpp ..\..\..\..\..\dll\steam_ugc.cpp ..\..\..\..\..\dl
         l\steam_unified_messages.cpp ..\..\..\..\..\dll\steam_user.cpp ..\..\..\..\..\dll\steam_user_stats.cpp ..\..\.
         .\..\..\dll\steam_user_stats_achievements.cpp ..\..\..\..\..\dll\steam_user_stats_leaderboard.cpp ..\..\..\..\
         ..\dll\steam_user_stats_stats.cpp ..\..\..\..\..\dll\steam_utils.cpp ..\..\..\..\..\dll\steam_video.cpp ..\..\
         ..\..\..\dll\ugc_remote_storage_bridge.cpp ..\..\..\..\..\helpers\common_helpers.cpp ..\..\..\..\..\helpers\db
         g_log.cpp
         win.cpp
         appticket.cpp
         auth.cpp
         base.cpp
         callsystem.cpp
     2>D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\deps\win\vs2022\mbedtls\install64\include\psa\crypto.h(110,29
       ): error C2526: 'psa_key_attributes_init': una funzione con collegamento C non può restituire la classe C++ 'psa
       _key_attributes_s' (compilazione del file di origine ..\..\..\..\..\dll\auth.cpp) [D:\Proyectos\Goldberg_emu_AoE
       _Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.vcxproj]
       D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\deps\win\vs2022\mbedtls\install64\include\psa\crypto_types.h(
       432): message : vedere la dichiarazione di 'psa_key_attributes_s' (compilazione del file di origine ..\..\..\..\
       ..\dll\auth.cpp) [D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.
       vcxproj]
     2>D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\deps\win\vs2022\mbedtls\install64\include\psa\crypto.h(939,29
       ): error C2526: 'psa_hash_operation_init': una funzione con collegamento C non può restituire la classe C++ 'psa
       _hash_operation_s' (compilazione del file di origine ..\..\..\..\..\dll\auth.cpp) [D:\Proyectos\Goldberg_emu_AoE
       _Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.vcxproj]
       D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\deps\win\vs2022\mbedtls\install64\include\psa\crypto.h(929):
       message : vedere la dichiarazione di 'psa_hash_operation_s' (compilazione del file di origine ..\..\..\..\..\dll
       \auth.cpp) [D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.vcxpro
       j]
     2>D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\deps\win\vs2022\mbedtls\install64\include\psa\crypto.h(1298,2
       8): error C2526: 'psa_mac_operation_init': una funzione con collegamento C non può restituire la classe C++ 'psa
       _mac_operation_s' (compilazione del file di origine ..\..\..\..\..\dll\auth.cpp) [D:\Proyectos\Goldberg_emu_AoE_
       Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.vcxproj]
       D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\deps\win\vs2022\mbedtls\install64\include\psa\crypto.h(1288):
        message : vedere la dichiarazione di 'psa_mac_operation_s' (compilazione del file di origine ..\..\..\..\..\dll
       \auth.cpp) [D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.vcxpro
       j]
     2>D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\deps\win\vs2022\mbedtls\install64\include\psa\crypto.h(1711,3
       1): error C2526: 'psa_cipher_operation_init': una funzione con collegamento C non può restituire la classe C++ '
       psa_cipher_operation_s' (compilazione del file di origine ..\..\..\..\..\dll\auth.cpp) [D:\Proyectos\Goldberg_em
       u_AoE_Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.vcxproj]
       D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\deps\win\vs2022\mbedtls\install64\include\psa\crypto.h(1701):
        message : vedere la dichiarazione di 'psa_cipher_operation_s' (compilazione del file di origine ..\..\..\..\..\
       dll\auth.cpp) [D:\Proyectos\Goldberg_emu_AoE_Crack\gbe_fork\build\project\vs2022\win\api_regular\api_regular.vcx
       proj]

**Comment by Chichimokers** [comment]
always i tried to build many times always the same error i install windows sdk 10.0.22621.175,and i have others sdk , 
this is mi msvc version
 -- Building for: Visual Studio 17 2022
-- The C compiler identification is MSVC 19.30.30709.0
-- The CXX compiler identification is MSVC 19.30.30709.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done

**Comment by alex47exe** [comment]
Not sure about building it offline, haven't yet tried to build the latest commit on my PC. I think you should first make sure you have all required packages and build tools for Visual Studio 2022, at least related to C++ development. Also make sure you have updated the submodules as well, not only the dev branch on your fork (use git clone --recurse-submodules https://github.com/Detanup01/gbe_fork.git). Building through the github actions works properly, without any error as you can see here, on my workflow run [https://github.com/alex47exe/gse_fork/actions/runs/10454678095](https://github.com/alex47exe/gse_fork/actions/runs/10454678095). I'll try to build it offline too, and let you know if it works for me.
--- Edit ---
yeah, it seems it only builds the release x64 version then it stops. and I'm sure I have everything up to date, including submodules

**Comment by Chichimokers** [comment]
The msvc is not latest version , i have installed all related packages to c++  version 17.0 , i use git clone use git clone --recurse-submodules https://github.com/Detanup01/gbe_fork.git too, i think that was the version of MSVC and build tools i will update all build tools an try  ,

**Comment by Detanup01** [comment]
I was able to build from recloning, rebuilding the deps and building the project.
