### ISSUE TITLE
[reminder] invalidate/delete current deps cache

### ISSUE THREAD

**Issue by otavepto** [Detanup01/gbe_fork#23]
These were created long time ago, latest PRs changed the deps.
Curl for example must now be rebuilt with mbedtls as SSL backend and `Sak32009` updated all deps archives
![image](https://github.com/user-attachments/assets/917ee152-eb13-4e3a-b4db-bf8c67dcf3ca)

You can then run both workflows `Emu third-party dependencies (Windows)` and `Emu third-party dependencies (Linux)` manually on the dev branch, must be the dev branch so that all other PRs/branches/tags can reuse that same cache, that's because the authors of the cache action tied the generated caches to the originating branch, except the main one (aka dev here).
More on that here: https://github.com/orgs/community/discussions/27059

By the way, you can easily create a release by pushing a tag with the pattern `release-****` to automate everything (except changelog):
https://github.com/Detanup01/gbe_fork/blob/f8c18b52e2e6c82fbd1ae85ea8ab41ba0c788696/.github/workflows/release.yml#L3-L6

I assume you already know this, but just in case not I'll mention it, the workflow `Prepare release` works in 2 modes, when you push a tag think of it as building in release mode, it will create an actual release and upload the files.
https://github.com/Detanup01/gbe_fork/blob/f8c18b52e2e6c82fbd1ae85ea8ab41ba0c788696/.github/workflows/release.yml#L80-L83

When you run it manually from the `Actions` tab, it will do everything except creating the release and uploading its artifacts (debug mode to test the output)
https://github.com/Detanup01/gbe_fork/blob/f8c18b52e2e6c82fbd1ae85ea8ab41ba0c788696/.github/workflows/release.yml#L87-L90

Example
```shell
# create the tag locally
git tag release-whatever-you-want

# push the tag to Github
git push origin release-whatever-you-want
```

Ping me here if things didn't work I'll help

**Comment by otavepto** [comment]
My favorite quotes from the cache discussion linked above

===

![image](https://github.com/user-attachments/assets/e14e3119-7792-46a2-a327-f0de6d357c23)

===

![image](https://github.com/user-attachments/assets/05de7f0f-92bf-470f-ac1c-db31582dff94)

===

![image](https://github.com/user-attachments/assets/0fae7528-ac26-4621-844d-18db96d7ca16)

**Comment by Detanup01** [comment]
Thank you for the first one. didnt know that! I run as I writing this.
For the Prepare Release I use it to check if actually buildable and works rather than actually creating a release (it already stays there 7 days)

**Comment by Sak32009** [comment]
Sorry about that, I stupidly forgot to mention that the cache needed to be rebuilt. 😕

**Comment by otavepto** [comment]
Wait the cache is still week old, are you sure you deleted it ?
