### ISSUE TITLE
err:msvcrt:_wassert (L"!status",L"./steamclient_main.c",356)

### ISSUE THREAD

**Issue by detiam** [Detanup01/gbe_fork#25]
After Proton 9.0 update, it no longer works with this emu.
by checking the log

```
34883.661:0168:016c:err:steamclient:steamclient_init unable to load Steam_IsKnownInterface
34883.661:0168:016c:err:msvcrt:_wassert (L"!status",L"./steamclient_main.c",356)
```

seems related to code [here](https://github.com/ValveSoftware/Proton/blame/962bbc4e74dde0643a6edab7c845bc628601f23f/lsteamclient/steamclient_main.c#L356), commit [cf89fdf018d500dfacd80ce48f35733bbb2baef0](https://github.com/ValveSoftware/Proton/commit/cf89fdf018d500dfacd80ce48f35733bbb2baef0#diff-721c03714e31f554fa890064479e8f9f9fa448ce1e940aa246b41020e36349d0L480).
I have no idea, can anyone help?

raw log: [log-proton8.log](https://github.com/user-attachments/files/16681306/log-proton8.log) [log-proton9.log](https://github.com/user-attachments/files/16681309/log-proton9.log)

**Comment by otavepto** [comment]
check the linked PR, the error was due to missing exports, I assume they were newly added.
