### ISSUE TITLE
Can't figure out how to allow the game to make external connections

### ISSUE THREAD

**Issue by thecatontheceiling** [Detanup01/gbe_fork#37]
I am currently trying to use HITMAN 3 with Goldberg (steamclient_experimental version)

Whenever the game tries to make a request it returns a 500 which is weird considering I have set both `disable_networking` and `disable_lan_only` to 1 in the config.

`[main::connectivity]
disable_lan_only=1
disable_networking=1
`

**Comment by thecatontheceiling** [comment]
Attached is my steam_settings folder
[steam_settings.zip](https://github.com/user-attachments/files/16965766/steam_settings.zip)

**Comment by thecatontheceiling** [comment]
I don't think i'm using the latest version of this fork, can't figure out where to check the version number though

**Comment by DogancanYr** [comment]
Download the latest version.
Do you use Peacock?
Also use the debug version.

**Comment by thecatontheceiling** [comment]
> Download the latest version. Do you use Peacock? Also use the debug version.

I use Peacock, yes. I want to get contracts mode lookup by ID working using the hitmaps website instead of official servers which used to work with otavepto's fork with the setup i linked above.

I just switched disable_networking to 0, still no dice.

I dont want to waste time getting latest version setup if it doesnt fix my issue, and i dont want to use the debug version for some reasons.

If there was a fix made for this bug (im assuming its a bug and not user error) then i will update to latest.

**Comment by thecatontheceiling** [comment]
Closing because the issue was not the steam emulator.
