### ISSUE TITLE
Add support for steam's lan game servers

### ISSUE THREAD

**Issue by elyashivhazan** [Detanup01/gbe_fork#41]
will it be able to add support for steam lan game server browser?

like in valheim the server supports 2 protocols: playfub (as of this date) after the last update playfab is not access able with goldberg emu and must be used with steam (kind of a drm only for mp) but the server also supports lan but with steam server browser. with that feature lan will be passable in valheim with dedicated server. do note that lan is still playable with hosting the world file one of the players host (but that host must play for someone else to play)

**Comment by Detanup01** [comment]
Already existing called "custom_broadcasts.txt"
you can add your/friends/vpn ip and broadcast address (ends with .255) to able to others to see it.
and lobby_connect also exist for this reason to see who and what users playing in the broadcasted network

**Comment by elyashivhazan** [comment]
ik about that, i play with my friends using zerotier and setting the mtu of the interface instead of using `custom_broadcasts.txt` (we dont play only with gbe)

my request is for this:
![20240915_211540+0300](https://github.com/user-attachments/assets/37378f13-cf85-474c-b704-a03c59093da8)
on steam client go to: `View` -> `Game Servers` and i would assume there is only a need to show lan, but i will also assume that steam uses the same code for `Internet` and `LAN` just flags to know what is what (not sure)"

EDIT: this is an example but more games then valheim use that
https://github.com/lloesche/valheim-server-docker?tab=readme-ov-file#steam-server-browser

adding this to the overlay or something like lobby_connect could be a way

**Comment by Detanup01** [comment]
goldberg doesnt use steam server thats the point of emulators!
Im not using overlay becasue I highly get crashes even when disabling everything that may hook into it.

Overlay using ImGUI. If you have time and know how to build that in imgui feel free to make a PR.

**Comment by elyashivhazan** [comment]
but isnt steam server lan running on client side? so isnt that the same?

as far as i can tell lan servers dont need internet so its all running on client side (unless im wrong)

**Comment by Detanup01** [comment]
even if you connected in lan. it still using steam connections, steam related functions.
Yes without internet you still can see others because steam client still broadcast information to broadcast networks. (192.168.1.255, 255.255.255.255, etc..)
That basicly how this emu do stuff with internet and how you can see others despite they are not next to you.

**Comment by elyashivhazan** [comment]
so my understanding was right. then why isnt showing dedicated servers broadcasting to steam client isnt a passability? unless the server is hard coded to broadcast to steam servers and then back to client just to show it (couldnt be its to inefficient)

**Comment by Detanup01** [comment]
because the goldberg emu intercepts any communication to the Steam Servers.
Anything the game asks, posts, is intercepted and using its goldergs solution.

**Comment by elyashivhazan** [comment]
look i will be perfectly honest im lost why its not passable :) but thank you very very much, i manged to switch the steamlib files in the server files with ur emu ad its working (i tried with the og mr goldberg's emu but it crash at startup assuming not implemented apis).

but this more modern one its working more then fine, thanks again.
