### ISSUE TITLE
Dead Cells not working with the experimental emulator

### ISSUE THREAD

**Issue by Mecak** [Detanup01/gbe_fork#44]
Hi, thanks for this great work ^__^
I tried to launch the game with the experimental version but I got this error message (it works with the original Goldberg):

`Unknown runtime error
Called from steam.ugc.Query.getResult (steam/ugc/Query.hx line 190)
Called from $Lang.~tryAutoInstallMod.1 (Lang.hx line 207)
Called from steam.ugc.Query.~send.0 (steam/ugc/Query.hx line 159)
Called from steam.ugc.Query.~send.1 (Achievements.hx line 0)
Called from haxe.$MainLoop.tick (D:\gitlab-runner\builds\UAYh7sUw\0\motion-twin\deadcells\client\.tools\haxe\std/haxe/MainLoop.hx line 174)
Called from hxd.$System.runMainLoop (hxd/System.hl.hx line 126)
Called from hxd.$System.runMainLoop (hxd/System.hl.hx line 123)
Called from haxe.$Timer.~delay.0 (D:\gitlab-runner\builds\UAYh7sUw\0\motion-twin\deadcells\client\.tools\haxe\std/haxe/Timer.hx line 143)
Called from haxe.$Timer.~__constructor__.0 (D:\gitlab-runner\builds\UAYh7sUw\0\motion-twin\deadcells\client\.tools\haxe\std/haxe/Timer.hx line 76)
Called from haxe.$MainLoop.tick (D:\gitlab-runner\builds\UAYh7sUw\0\motion-twin\deadcells\client\.tools\haxe\std/haxe/MainLoop.hx line 174)
Called from haxe.$EntryPoint.processEvents (D:\gitlab-runner\builds\UAYh7sUw\0\motion-twin\deadcells\client\.tools\haxe\std/haxe/EntryPoint.hx line 99)
Called from haxe.$EntryPoint.run (D:\gitlab-runner\builds\UAYh7sUw\0\motion-twin\deadcells\client\.tools\haxe\std/haxe/EntryPoint.hx line 125)`

When I tried with the steamclient_experimental it only works when I use steamless on the game.exe otherwise it also gives an error message : 
`Steam Error
Application load error 3:0000065432`

**Comment by Mecak** [comment]
I managed to get it work with the experimental emulator with these parameters

```
# prevent hooking OS networking APIs and allow any external requests
disable_lan_only=0
# pretend steam is running in offline mode
offline=1
```

The opposite of these parameters works with the steamclient_experimental and the online features works perfectly

Without the online features we will get always this message on the main menu

![online deactivated 1](https://github.com/user-attachments/assets/77b88c3d-189a-462e-894f-8afd364e7a48)

With the online features we won't get it and also we got other information like new update logs and the daily challenge ranking 

![online activated 1](https://github.com/user-attachments/assets/92cc8bab-ea2f-4a7e-bb35-d71a9825e36a)
![online activated 2](https://github.com/user-attachments/assets/043a1259-4b77-41a5-a3cf-40f61f97de21)

**Comment by Detanup01** [comment]
Yeah, because the game make requests for real DeadCell servers and with disable_lan_only=0 you enable it to call functions outside of LAN network, ergo online functions.

I only use it for true offline, ie: No connection to any servers, LAN only.

> Steam Error Application load error 3:0000065432

Yes usual CEG error. Need steamless to make it work.
