### ISSUE TITLE
God of War Ragnarök : Crash on startup

### ISSUE THREAD

**Issue by Mecak** [Detanup01/gbe_fork#46]
Hi, Thanks for your great work 
I tried to launch the game with the latest version of the emulator but it always crashes
It works correctly with the original Goldberg emulator
This is the log file attached

[STEAM_LOG_2869757345.log](https://github.com/user-attachments/files/17114423/STEAM_LOG_2869757345.log)

I also noticed that the font Roboto-Medium.ttf always not detected, I already have a folder name fonts and contains the font

**Comment by Detanup01** [comment]
Can you share your settings + interfaces?
thx

**Comment by Mecak** [comment]
Sorry I found the problem
I have to add these information in configs.main.ini

```
# generate new app auth ticket
new_app_ticket=1
# generate/embed GC token inside new App Ticket
gc_token=1
```

Also it resolve the error when loading the font

**Comment by otavepto** [comment]
@Detanup01 Thank you a lot for implementing the new ticket format, this is becoming more and more necessary and I know you won't get enough appreciation for it.

**Comment by Detanup01** [comment]
:D
Maybe we could do is check interface versions and use the new ticket option since like Client020+ it's using that, but thats just a throught.

**Comment by Detanup01** [comment]
Oh for ragnarök, i recommend the no sonysdk mod

**Comment by Mecak** [comment]
Thanks, I already use the latest version of nopssdk v1.0.2 published yesterday
