### ISSUE TITLE
Use feature/detect-dxvk branch of ingame_overlay

### ISSUE THREAD

**Issue by Edremon** [Detanup01/gbe_fork#48]
I was waiting for it to be merged in master, but not sure if that will happen soon. This branch https://github.com/Nemirtingas/ingame_overlay/tree/feature/detect-dxvk allow the overlay to work correctly when using dxvk, this is essential for linux users to get overlay in games. Overlay as been broken on this fork since it switched to use ingame_overlay as an external library, this will finally allow linux user to have overlay back when using this fork.

On a side note, why are dependencies in some archives? Would be easier to include them as git submodules.

**Comment by Detanup01** [comment]
Archives because those can be deleted at any time. (Submodules, gits)
Originally done by Wizard so I have to ask him about this.

**Comment by otavepto** [comment]
@Detanup01 I added all deps as archives because history taught me that anything could be deleted at anytime for one reason or another (copyright problem, migration to another host, some unknown conflict, etc...)
Another reason is for the repo to be self-contained, this was just a personal taste/preference.
Just do whatever you want/see fit anytime, this is your fork.

Oh hey I forgot this line in the readme 😛😛😛😛😛😛  
![image](https://github.com/user-attachments/assets/75a29bad-2c0c-49ec-8d0c-16e5738c22d7)

**Comment by Edremon** [comment]
Wouldn't releasing a source tar ball on each release with the full source solve that problem? I believe that common enough for projects with submodules as github provided one don't have those cloned. But, it's not super important anyway, archives work fine, I just find them annoying to work with, but I'm not a big contributor to this project.

**Comment by M4RCK5** [comment]
Wait so using this and DXVK could fix a lot of the issues with the overlay not only for linux but for windows too??

**Comment by Detanup01** [comment]
If you willing to update the common deps to that version i be happy so can build with it (Or even you could do the same and verifying it works)
Or you can start redoing the archives to be git modules.
Either one is good for me

**Comment by Detanup01** [comment]
Check new Release
(since it already added  to main i just used that)

**Comment by Edremon** [comment]
Completely forgot to answer your previous questions. I had been using gbe_fork compiled on feature/detect-dxvk for a while now, everything work correctly on my machine, you can see some of my tries and another user using it here https://github.com/Nemirtingas/ingame_overlay/pull/41.

> Check new Release

You didn't update the git submodule, you only updated the deps branch, this is still using old version.

**Comment by Detanup01** [comment]
nice and fuck

**Comment by DogancanYr** [comment]
> Completely forgot to answer your previous questions. I had been using gbe_fork compiled on feature/detect-dxvk for a while now, everything work correctly on my machine, you can see some of my tries and another user using it here [Nemirtingas/ingame_overlay#41](https://github.com/Nemirtingas/ingame_overlay/pull/41).
> 
> > Check new Release
> 
> You didn't update the git submodule, you only updated the deps branch, this is still using old version.

I'm just asking out of curiosity.
Why does git submodule need to be updated and what happens if it is not updated ?

**Comment by Detanup01** [comment]
Git submodules is never update automatically.
You need to update them. (With commands)

If not updated it stays on that version that was already there, and when updated all files comes there too

**Comment by Edremon** [comment]
I don't know what you did but the .tar.gz is not f819c89, it is, I believe 16260d8.

It's exactly the same content as old one with a different modification date on directories.

**Comment by Detanup01** [comment]
It is literally the master zipped and rezipped. Nothing changed on that. (Except that commit)

Anyway if works work if not others will make a PR if not then idc at this point

**Comment by Edremon** [comment]
It is not. You can literally see the exact same modification date on files and the exact same contents as previous .tar.gz.

**Comment by debugzxcv** [comment]
Steps to archive ingame_overlay git repo:
1. `git clone -j8 --recurse-submodules https://github.com/Nemirtingas/ingame_overlay ingame_overlay`
2. `cd ingame_overlay; curl -sL https://github.com/fabacab/git-archive-all.sh/raw/refs/heads/master/git-archive-all.sh | bash -s -- -v --prefix ingame_overlay/ --format tar.gz`
[ingame_overlay.tar.gz](https://github.com/user-attachments/files/17689847/ingame_overlay.tar.gz)

**Comment by Edremon** [comment]
Just `tar -czvf ingame_overlay.tar.gz ingame_overlay`. Why are you executing random shell script from the internet?

**Comment by debugzxcv** [comment]
> Just `tar -czvf ingame_overlay.tar.gz ingame_overlay`. Why are you executing random shell script from the internet?

This will contain .git folder

**Comment by puyebu** [comment]
Been trying to get the overlay to work with dxvk but I don't understand what do I need to do?
The latest release does not contain working overlay for me.
