### ISSUE TITLE
EMU_MISSING_INTERFACE

### ISSUE THREAD

**Issue by KiNGKiMO** [Detanup01/gbe_fork#54]
Trying Counter-Strike 2 gives this error about missing interface, and here are the contents of EMU_MISSING_INTERFACE.txt file:

INTERFACE=SteamAppDisableUpdate001
CALLER FN=Steam_Client::GetISteamGenericInterface()
APPID=730
TIME=2024/10/09 - 06:23:11
--------------------

**Comment by Detanup01** [comment]
Seems like CS specific. Will see what can I do with it

**Comment by KiNGKiMO** [comment]
Thanks so much for your efforts.
I've noticed that it works with old goldberg emulator, strange eh?

**Comment by forgotthepen** [comment]
My favorite type of issues
![20241009_155011](https://github.com/user-attachments/assets/dc9956c4-c614-4686-b6ed-f0166fd7a803)

Only public thing I could find
https://github.com/Hackerprod/-SKYNET-Steam-Emulator/blob/5ec2006efd322e3ea9f4fff8fa07ea8fb4cf9b4d/steam_api/Steamworks/Interfaces/SteamAppDisableUpdate001.cs#L9

Honestly better grab the vftable from real client, save each address, and check each function in Ghidra/IDA.
