### ISSUE TITLE
SteamAppDisableUpdate001 - CS2

### ISSUE THREAD

**Issue by VladimirEve** [Detanup01/gbe_fork#56]
INTERFACE=SteamAppDisableUpdate001
CALLER FN=Steam_Client::GetISteamGenericInterface()
APPID=730
TIME=2024/10/12 - 10:18:23

**Comment by Detanup01** [comment]
#55

**Comment by Detanup01** [comment]
Not released yet but you can download the Action

**Comment by VladimirEve** [comment]
thanks

INTERFACE=STEAMUGC_INTERFACE_VERSION019
CALLER FN=Steam_Client::GetISteamUGC()
APPID=730
TIME=2024/10/12 - 12:45:28

**Comment by Detanup01** [comment]
nice, it doesnt exists in public
