### ISSUE TITLE
Another EMU_MISSING_INTERFACE 

### ISSUE THREAD

**Issue by KiNGKiMO** [Detanup01/gbe_fork#62]
Trying Counter-Strike 2 gives this error about missing interface after  you guys fixed the missing "SteamAppDisableUpdate001" interface, and here are the contents of EMU_MISSING_INTERFACE.txt file:

INTERFACE=STEAMUGC_INTERFACE_VERSION019
CALLER FN=Steam_Client::GetISteamUGC()
APPID=730
TIME=2024/10/19 - 20:45:16
--------------------

**Comment by Detanup01** [comment]
Lates release should fix this
