### ISSUE TITLE
Missing SteamUtils001 Interface

### ISSUE THREAD

**Issue by alex47exe** [Detanup01/gbe_fork#63]
> WWE 2K24 tried your fork but having problem, game shutdown itself with this error, can you help me ?
> 
> ![image](https://private-user-images.githubusercontent.com/72945555/378228125-4c53d034-3dc0-4930-8485-82720877e6bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NjY3MjUsIm5iZiI6MTcyOTQ2NjQyNSwicGF0aCI6Ii83Mjk0NTU1NS8zNzgyMjgxMjUtNGM1M2QwMzQtM2RjMC00OTMwLTg0ODUtODI3MjA4NzdlNmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDIzMjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNjcxZWZkMWQyZWRkOTY2YTE0OTVkYjk5YzQ2NTdiM2VjMDg0YmQ3NzQzZjIzNTEwOGExNTFjYWM5MDJmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1tJ6bOQqRxDuVqKSjmfuj5gicyInxK4eyrSdpw0qJ5M)

Reported by @MrStrangerx on my fork. I'm reporting back here, since unfortunately I'm not quite good with C++ to modify the emulator side of the fork.

**Comment by Detanup01** [comment]
Actually what the fuck

**Comment by Detanup01** [comment]
Game file has SteamUser023. Even interface generating V23.
What the fuck does the game do that wrong it calling V4????????????????????

**Comment by MrStrangerx** [comment]
I am sorry I really dont know why this is happening ?

**Comment by Detanup01** [comment]
Ye me too, I dont know why is it even happened.
There is no way that the 2024 games call a 201x version of interface.

**Comment by MrStrangerx** [comment]
How can I solve this issue :) Any idea :)

**Comment by universal963** [comment]
Even the earliest public sdk, which is sdk 1.00, contains as new interface as `SteamUser009`, so I presume if it is not called on purpose, it must be some private sdk before 1.00. Although I have tested on real steam that such old undocumented interface is indeed valid.

Edit: found it here: https://github.com/ValveSoftware/Proton/blob/proton_9.0/lsteamclient/steamworks_sdk_099u/isteamuser.h

**Comment by Detanup01** [comment]
Why they using such and old interface in 2024?
I have 0 idea why they calling that

**Comment by Detanup01** [comment]
@MrStrangerx can you please check the Builds that the PR Made by universal?

**Comment by MrStrangerx** [comment]
> @MrStrangerx can you please check the Builds that the PR Made by universal?

I am sorry I didn't understand what I have to do, sorry have a little knowledge :)

**Comment by Detanup01** [comment]
go to https://github.com/Detanup01/gbe_fork/actions/runs/11459618875?pr=64
and download the api win, x64 and experimental one. (prob this is good: https://github.com/Detanup01/gbe_fork/actions/runs/11459618875/artifacts/2087630214)
unzip, replace that .dll to the one from old goldberg , run the game again

**Comment by MrStrangerx** [comment]
![image](https://github.com/user-attachments/assets/9f8799f4-df12-45d3-9fa6-4d8e77209b23)

Tried and now having this error ?

> go to https://github.com/Detanup01/gbe_fork/actions/runs/11459618875?pr=64 and download the api win, x64 and experimental one. (prob this is good: https://github.com/Detanup01/gbe_fork/actions/runs/11459618875/artifacts/2087630214) unzip, replace that .dll to the one from old goldberg , run the game again

**Comment by Detanup01** [comment]
I already hate this game

**Comment by Detanup01** [comment]
Well can you try this now?
https://github.com/Detanup01/gbe_fork/actions/runs/11466213394

**Comment by universal963** [comment]
> Well can you try this now? https://github.com/Detanup01/gbe_fork/actions/runs/11466213394

You seem to have forgot modifications on interface getter, so mostly it won't work

**Comment by Detanup01** [comment]
Ah forgot

**Comment by MrStrangerx** [comment]
I am sorry which one I should download ?

**Comment by Detanup01** [comment]
This
https://github.com/Detanup01/gbe_fork/actions/runs/11482655859
Same option your choose from older one but with different id after file name

**Comment by MrStrangerx** [comment]
All of them looking Expired or am I wrong ? Could you show in pictures how can I download correct version ?

**Comment by Detanup01** [comment]
Y'know what I just merge it tomorrow

**Comment by MrStrangerx** [comment]
![image](https://github.com/user-attachments/assets/68523e86-e858-4eb5-bc94-75964affe9f0)

I am sorry. I downloaded new release(coppied dll), Generated steam settings, generated interface, copied .ini settings deleted example sections,New error appeared :(

**Comment by universal963** [comment]
I wonder if this game requires old versions of all interfaces now......

**Comment by MrStrangerx** [comment]
How can I do that :)))))

**Comment by DogancanYr** [comment]
Denuvo VS old interfaces.

(I think scene emulators work.)

**Comment by universal963** [comment]
> How can I do that :)))))

A PR is on the way for this interface now, no ideas what's next interface waiting for us

**Comment by Detanup01** [comment]
Next would be ISteamFuckYouPiratesV001

**Comment by DogancanYr** [comment]
> Next would be ISteamFuckYouPiratesV001

Denuvo: 0
Old interfaces: 1

By the way, thanks for your works.
