### ISSUE TITLE
[bug] buffer overrun when retrieving mod/UGC details + missing UGC callback on failure

### ISSUE THREAD

**Issue by otavepto** [Detanup01/gbe_fork#65]
add different variants for
* `Steam_UGC::GetQueryUGCResult()`
* `Steam_UGC::RequestUGCDetails()`

to support the changed struct layout for mod details after `sdk 1.60`.  
that one damn new struct member `m_ulTotalFilesSize ` broke support for all mods, and sometimes trips the stack-cookie check routine found at the epilogue of most asm routines
https://github.com/Detanup01/gbe_fork/blob/2b0eefd929ce840ffac78886f11b713dbf0215de/dll/steam_ugc.cpp#L109-L111
after sdk 1.60 that struct is now +8 extra bytes, but games/apps using older sdks (which is almost every game out there) will only allocate memory big enough for the older struct size.
and since the emu overwrites these 8 bytes, it is considered illegal access operation, and in fact this memory location is usually somewhere on the stack, and as seen in appid 588650, could be the usual stack cookie/canary.

some games like appid 588650 expect a callback + call-result to be triggered with failure result (`data.m_eResult = k_EResultFail`) here instead of returning an invalid ID
https://github.com/Detanup01/gbe_fork/blob/2b0eefd929ce840ffac78886f11b713dbf0215de/dll/steam_ugc.cpp#L233-L242

here, we must init `pDetails->m_eResult` struct member to `k_EResultFail` since appid 588650 ignores the return of the function and looks for the value in that member
https://github.com/Detanup01/gbe_fork/blob/2b0eefd929ce840ffac78886f11b713dbf0215de/dll/steam_ugc.cpp#L278-L282

I'll fix these, just leaving a note since I forget every time.

**Comment by otavepto** [comment]
This was the primary reason for #44 btw

**Comment by Detanup01** [comment]
Thank you!
