### ISSUE TITLE
DOTA 2 - STEAMTIMELINE_INTERFACE_V002

### ISSUE THREAD

**Issue by VladimirEve** [Detanup01/gbe_fork#69]
INTERFACE=STEAMTIMELINE_INTERFACE_V002
CALLER FN=Steam_Client::GetISteamTimeline()
APPID=570
TIME=2024/10/23 - 09:48:39
--------------------

**Comment by Detanup01** [comment]
How.
Only v1 is public?

**Comment by universal963** [comment]
BTW, I personally somehow understand why Mr.Goldberg didn't care about csgo (cs2) or dota2 now.

**Comment by Detanup01** [comment]
Wait until the V002 function is available for the Public Partners. Until then I close this since cant actually do it.
(Easier to wait until its public than download the game, reverse it, etc)

(Game actually doesnt show any new interface, might be thry updated the enums and such)
