### ISSUE TITLE
DOTA2 Game Coordinator

### ISSUE THREAD

**Issue by Svenmax** [Detanup01/gbe_fork#70]
hello.
Can these be used for developing DOTA2 Game Coordinator?

Thx.
https://github.com/Hackerprod/-SKYNET-Steam-Emulator
[steam_api.zip](https://github.com/user-attachments/files/17504732/steam_api.zip)

**Comment by Detanup01** [comment]
Original:
Have fun with it

Detailed:
You need to create a server for Dota2 GC. Also you might need to emulate the server itself since probably gonna request stuff from Steam Web API.
I dont have enough time and supporting games that has Game Coordinator or 3rd Party servers are now closed.

**Comment by Svenmax** [comment]
Thanks.
