### ISSUE TITLE
Missing Interface STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001

### ISSUE THREAD

**Issue by kelp-o** [Detanup01/gbe_fork#72]
Trying to run the latest Version of No more Room in Hell ( https://store.steampowered.com/app/224260/No_More_Room_in_Hell/ ) throws following error on launch:

---------------------------
Missing interface
---------------------------
INTERFACE=STEAMUNIFIEDMESSAGES_INTERFACE_VERSION001
CALLER FN=Steam_Client::GetISteamHTTP()
APPID=224260
TIME=2024/10/25 - 10:58:33
--------------------

---------------------------
OK   
---------------------------

**Comment by Detanup01** [comment]
Are you sure you generated interface.txt?

**Comment by kelp-o** [comment]
yes, the exxport will not be detected by generate_interfaces_x32.exe and manually adding it to steam_interfaces.txt doesn't work either

**Comment by Detanup01** [comment]
Please give me the logs made by the debug one.
Also if this using GC i will close this as fast as possible

**Comment by kelp-o** [comment]
[STEAM_LOG_3279383230.log](https://github.com/user-attachments/files/17529109/STEAM_LOG_3279383230.log)

here is the log

**Comment by Detanup01** [comment]
ye I have 0 idea why it wants unified, It aint even asking in the logs

**Comment by universal963** [comment]
Maybe your `steam_interfaces.txt` is wrong. Remove line "SteamClient020" and try again?

**Comment by kelp-o** [comment]
that worked :D thanks
