### ISSUE TITLE
Steam_UGC::DownloadItem should trigger a DownloadItemResult_t callback

### ISSUE THREAD

**Issue by normanr** [Detanup01/gbe_fork#79]
`Steam_UGC::DownloadItem` currently just returns false, it would be nice if it returned true, and triggered a DownloadItemResult_t callback. This would make it easier to test in-game workflows that trigger a download.

**Comment by Detanup01** [comment]
I tried running DownloadItem probably like on v157, didn't do much on my testing with mods.

But feel free to create a PR and if works for your can merge it

**Comment by normanr** [comment]
Finally got around to testing this. It works great, thanks!
