### ISSUE TITLE
Global custom broadcasts

### ISSUE THREAD

**Issue by mironsaid** [Detanup01/gbe_fork#84]
Is there a way to add global custom broadcasts like in the original goldberg emu?

**Comment by Detanup01** [comment]
That still did not changed.

post_build/steam_settings.EXAMPLE/custom_broadcasts.EXAMPLE.txt

**Comment by mironsaid** [comment]
So ```%appdata%/GSE Saves/settings/custom_broadcasts.txt``` will apply to the entire emulator?

**Comment by Detanup01** [comment]
I guess might be the path is wrong (from settings to steam_settings) but no idea about that.

**Comment by mironsaid** [comment]
Confirmed by using the debug version of the emulator, thank you <3
