### ISSUE TITLE
EMU_MISSING_INTERFACE - STEAMTIMELINE_INTERFACE_V004

### ISSUE THREAD

**Issue by MavisCelus19201** [Detanup01/gbe_fork#87]
Ran into this while trying to run Half Life 2's newest build. Generating an interface.txt didn't work even using the newest build but I don't know if that's an issue on my end or if it's something unimplimented.

**Comment by universal963** [comment]
This interface is new and in public sdk 1.61, which is out at 2024/11/08. Need to be implemented here accordingly.

**Comment by Detanup01** [comment]
interface has been implemented but cant actually do a proper release bc of #89
probably you can try and download right version from github action and test I guess

**Comment by Detanup01** [comment]
Build shared on rin and many game worked with this "nonvalid impl"
