### ISSUE TITLE
Wrapper Mode?

### ISSUE THREAD

**Issue by DartPower** [Detanup01/gbe_fork#94]
Can you add Wrapper mode? e.g. using original steam_api functions with wrap to appid like 480, just like online fix?

**Comment by Detanup01** [comment]
Nope.
Otherwise this wouldnt be an option for offline/lan play. There is CreamAPI and possible other for this.
The code is public here. Feel free to make it a project of yours.

**Comment by DartPower** [comment]
>There is CreamAPI and possible other for this.

Them is proprietary :(
